In [1]:
import numpy as np
import pandas as pd

In [1]:
test = "這是測試字串, 測試測試測試"
result = {}

In [2]:
for c in test:
    try:
        result[c] = result[c] + 1
    except:
        result[c] = 1
print(result)

{'這': 1, '是': 1, '測': 4, '試': 4, '字': 1, '串': 1, ',': 1, ' ': 1}


In [11]:
def test(**args):
    print(args)

In [12]:
test(a=5,b=6,c=5)

{'a': 5, 'b': 6, 'c': 5}


In [16]:
? pd

In [19]:
np.*load*?

In [21]:
%run PCA+ruptures.ipynb

<Figure size 1000x800 with 4 Axes>

[0.99244289 0.00755711]
[0.99244289]


In [22]:
a = ["apple","banana","pear"]
b = {}

In [27]:
for i,v in enumerate(a):
    b[v] = i
print(b)

{'apple': 0, 'banana': 1, 'pear': 2}


In [28]:
a = ["apple","banana","pear"]
b = ["15","20","63"]

In [29]:
z = zip(a,b)

In [31]:
list(z)

[('apple', '15'), ('banana', '20'), ('pear', '63')]

In [35]:
for i,(x,y) in enumerate(zip(a,b)):
    print("{0}:{1},{2}".format(i,x,y))

0:apple,15
1:banana,20
2:pear,63


In [42]:
a = ["addae","dfa","kik","ok"]

In [43]:
b = [x.upper() for x in a if len(x)>2]

In [44]:
b

['ADDAE', 'DFA', 'KIK']

In [45]:
set(map(len,a))

{2, 3, 5}

In [48]:
loc_map = {index:val for index,val in enumerate(a)}

In [49]:
loc_map

{0: 'addae', 1: 'dfa', 2: 'kik', 3: 'ok'}

In [16]:
a = ["addae","dfa","kik","ok"]

In [20]:
a.sort(key=lambda x:len(set(list(x))))

In [21]:
def add_number(x,y):
    return x+y

In [23]:
o = add_number(5,6)

In [24]:
o

11

In [26]:
k = lambda y: add_number(5,y)

In [27]:
k

<function __main__.<lambda>(y)>

In [29]:
# 成形機台控制器全部數據
df = pd.read_csv("machine_input.csv")
# 射出系統健康值(II)
df_inj = df[["EL_PLST_END_ERR","EL_INJ_START_STR","EL_MAX_INJ_PRESS","EL_IV_TIME","EL_IV_END_PRESS","EL_VPS_END_STR","EL_MIN_INJ_STR","EL_GET_PART_TIME","EL_VPS_TIME","EL_PLST_TIME"]]

# 鎖模系統健康值
f_clamp = df[["EL_LAST_COOL_TIME","EL_MC_TIME","EL_MO_TIME","EL_EF_TIME","EL_EB_TIME","EL_IDLE_TIME","EL_CLAMP_PRESS","EL_MOP"  ]]


In [32]:
df_inj.loc[:,"EL_PLST_END_ERR"].values

array([79.95129 , 80.05457 , 80.06053 , 79.907585, 80.05457 , 80.008896,
       79.94731 , 80.05855 , 79.92547 , 80.06053 , 80.01286 , 80.06053 ,
       80.06649 , 79.95129 , 79.91752 , 79.88375 , 80.06053 , 80.03074 ,
       80.01088 , 80.03868 , 80.05457 , 80.02478 , 79.871826, 80.048615,
       79.90163 , 80.0367  , 80.02478 , 80.05258 , 79.91752 , 80.048615,
       79.93142 , 80.042656, 79.95923 , 80.01088 , 80.048615, 80.01286 ,
       79.97909 , 79.97511 , 79.94731 , 80.06053 , 80.06053 , 80.06053 ,
       79.96519 , 79.93738 , 79.93738 , 80.06053 , 79.99101 , 80.05656 ,
       79.89766 , 80.0367  , 79.99698 , 79.98903 , 80.040665, 80.02478 ,
       80.02478 , 79.95923 , 79.90163 , 80.028755, 79.977104, 80.05457 ,
       80.05457 , 80.048615, 79.94533 , 79.963196, 80.03074 , 79.985054,
       79.96718 , 80.06053 , 80.06053 , 79.89964 , 79.92149 , 80.03471 ,
       80.05457 , 80.05457 , 79.85594 , 80.06053 , 80.042656, 79.99896 ,
       80.04464 , 79.97909 , 79.87779 , 80.05457 , 

In [34]:
data = pd.DataFrame({"x1":[1,2,3],"x2":[0.25,0.3,0.12],"x3":[1.6,5.6,3.9]})

In [37]:
data["category"] = pd.Categorical(["a","b","a"],categories=["a","b"])

In [38]:
data

x1    x2   x3 category
0   1  0.25  1.6        a
1   2  0.30  5.6        b
2   3  0.12  3.9        a

In [39]:
dummies = pd.get_dummies(data.category,prefix="category")

In [41]:
data_with_dummies = data.drop("category",axis=1).join(dummies)

In [42]:
data_with_dummies

x1    x2   x3  category_a  category_b
0   1  0.25  1.6           1           0
1   2  0.30  5.6           0           1
2   3  0.12  3.9           1           0

In [43]:
data1 = pd.DataFrame({"x1":[0.1,1.2,0.3],"x2":[0.25,0.3,0.12],"y":[1.6,5.6,3.9]})

In [44]:
import patsy

In [45]:
y,X = patsy.dmatrices("y~x1+x2",data1)

In [46]:
y

DesignMatrix with shape (3, 1)
    y
  1.6
  5.6
  3.9
  Terms:
    'y' (column 0)

In [48]:
X

DesignMatrix with shape (3, 3)
  Intercept   x1    x2
          1  0.1  0.25
          1  1.2  0.30
          1  0.3  0.12
  Terms:
    'Intercept' (column 0)
    'x1' (column 1)
    'x2' (column 2)

In [49]:
coef,resid,_,_ = np.linalg.lstsq(X,y)

C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [50]:
coef

array([[  4.01176471],
       [  4.1503268 ],
       [-11.30718954]])

In [55]:
y,X = patsy.dmatrices("y~ standardize(x1) + center(x2) ",data1)

In [56]:
X

DesignMatrix with shape (3, 3)
  Intercept  standardize(x1)  center(x2)
          1         -0.90575     0.02667
          1          1.39347     0.07667
          1         -0.48771    -0.10333
  Terms:
    'Intercept' (column 0)
    'standardize(x1)' (column 1)
    'center(x2)' (column 2)

In [5]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [6]:
def dnorm(mean,variance,size=1):
    if isinstance(size,int):
        size=size,
    return mean+np.sqrt(variance)*np.random.randn(*size)

In [7]:
np.random.seed(123)

In [9]:
N = 100
X = np.c_[dnorm(0,0.4,size=N),
          dnorm(0,0.6,size=N),
          dnorm(0,0.2,size=N)]
eps = dnorm(0,0.1,size=N)
beta = [0.1,0.3,0.5]
y = np.dot(X,beta)+eps

In [11]:
X_model = sm.add_constant(X)

In [12]:
X_model[0:5]

array([[ 1.        , -0.68661308,  0.49733342,  0.31452985],
       [ 1.        ,  0.63077665, -1.5320654 , -0.26748084],
       [ 1.        ,  0.17897132,  0.55171781,  0.9841839 ],
       [ 1.        , -0.95266442,  2.01263757,  0.30781574],
       [ 1.        , -0.36593893, -0.0190752 , -0.00282069]])

In [13]:
model = sm.OLS(y,X)

In [14]:
result = model.fit()

In [16]:
result.params

array([0.05792223, 0.33219218, 0.62269232])

In [17]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.651
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     60.44
Date:                Mon, 19 Nov 2018   Prob (F-statistic):           4.04e-22
Time:                        16:06:10   Log-Likelihood:                -12.064
No. Observations:                 100   AIC:                             30.13
Df Residuals:                      97   BIC:                             37.94
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0579      0.039      1.488      0.140      -0.019       0.135
x2             0.3322      0.037      9.002      0.000       0.259       0.405
x3             0.6227      0.064      9.764      0.000       0.496       0.749
==============================================================================
Omnibus:                        0.659   Durbin-Watson:                   2.291
Prob(Omnibus):                  0.719   Jarque-Bera (JB):                0.709
Skew:                           0.187   Prob(JB):                        0.701
Kurtosis:                       2.825   Cond. No.                         1.73
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
data = pd.DataFrame(X,columns=["col0","col1","col2"])

In [20]:
data["y"] = y

In [21]:
results = smf.ols("y~col0+col1+col2",data=data).fit()

In [22]:
results.params

Intercept   -0.036185
col0         0.058819
col1         0.331359
col2         0.614709
dtype: float64

In [23]:
results.tvalues

Intercept   -1.303453
col0         1.516617
col1         9.010801
col2         9.629346
dtype: float64

In [27]:
results.predict(data[:5])

0    0.281569
1   -0.671169
2    0.762145
3    0.763903
4   -0.065764
dtype: float64

In [4]:
# kaggle tianic 
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
# submit = pd.read_csv("gender_submission.csv")

In [36]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [38]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [5]:
input_value = train["Age"].median()

In [6]:
train["Age"] = train["Age"].fillna(input_value)
test["Age"] = test["Age"].fillna(input_value)

In [7]:
train["IsFemale"] = (train["Sex"]=='female').astype(int)
test["IsFemale"] = (test["Sex"]=='female').astype(int)

In [8]:
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'IsFemale'],
      dtype='object')

In [9]:
predictors = ["Pclass","IsFemale","Age"]

In [10]:
X_train = train[predictors].values
X_test = test[predictors].values
y_train = train["Survived"].values

In [13]:
X_train.shape

(891, 3)

In [14]:
y_train.shape

(891,)

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
model = LogisticRegression()

In [56]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [73]:
y_true = submit["Survived"]

In [57]:
y_predict = model.predict(X_test)

In [74]:
( y_true == y_predict).mean() 

0.9712918660287081

In [59]:
# 多了交叉驗證
from sklearn.linear_model import LogisticRegressionCV

In [60]:
model_cv = LogisticRegressionCV(10)

In [61]:
model_cv.fit(X_train,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [62]:
y_cv_predict = model_cv.predict(X_test)

In [71]:
y_true = submit["Survived"]

In [72]:
( y_true == y_cv_predict).mean() 

0.9401913875598086

In [10]:
# Bitly-USA.gov example
import json
import pandas as pd
import numpy as np

In [8]:
path = "/Users/USER/Desktop/box/record.txt"

records = [json.loads(line) for line in open(path) ]

In [11]:
frame = pd.DataFrame(records)

In [17]:
result = pd.Series( x.split()[0] for x in frame.a.dropna())

In [21]:
result.value_counts()

Mozilla/5.0                                          2594
Mozilla/4.0                                           601
GoogleMaps/RochesterNY                                121
Opera/9.80                                             34
TEST_INTERNET_AGENT                                    24
GoogleProducer                                         21
Mozilla/6.0                                             5
BlackBerry8520/5.0.0.681                                4
BlackBerry8520/5.0.0.592                                3
Dalvik/1.4.0                                            3
Acoon                                                   2
BlackBerry9630/5.0.0.975                                2
Socialite/7766                                          2
Goldfire                                                2
LG-GW382f/V10d                                          1
Vodafone/1.0/LG-KU990i/V10c                             1
BlackBerry9530/5.0.0.328                                1
BlackBerry9300

In [22]:
cframe = frame[frame.a.notnull()]

In [27]:
cframe['os'] = np.where(cframe['a'].str.contains('Windows'),'Windows','Not Windows')

c:\users\user\anaconda3\envs\tensorflow-gpu\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
cframe['os']

0           Windows
1       Not Windows
2           Windows
3       Not Windows
4           Windows
5           Windows
6           Windows
7           Windows
8       Not Windows
9           Windows
10          Windows
11      Not Windows
12          Windows
14          Windows
15          Windows
16          Windows
17      Not Windows
18      Not Windows
19          Windows
20          Windows
21      Not Windows
22          Windows
23      Not Windows
24          Windows
25          Windows
26          Windows
27      Not Windows
28      Not Windows
29      Not Windows
30          Windows
           ...     
3529        Windows
3530        Windows
3531    Not Windows
3532        Windows
3533    Not Windows
3534    Not Windows
3535        Windows
3536    Not Windows
3537        Windows
3538    Not Windows
3539    Not Windows
3540        Windows
3541    Not Windows
3542        Windows
3544        Windows
3545        Windows
3546    Not Windows
3547    Not Windows
3548    Not Windows


In [29]:
by_tz_os = cframe.groupby(['tz','os'])

In [35]:
agg_counts = by_tz_os.size().unstack().fillna(0)

In [43]:
indexer = agg_counts.sum(1).argsort()

In [45]:
count_subset = agg_counts.take(indexer[-10:])

In [46]:
count_subset 

os                   Not Windows  Windows
tz                                       
America/Sao_Paulo           13.0     20.0
Europe/Madrid               16.0     19.0
Pacific/Honolulu             0.0     36.0
Asia/Tokyo                   2.0     35.0
Europe/London               43.0     31.0
America/Denver             132.0     59.0
America/Los_Angeles        130.0    252.0
America/Chicago            115.0    285.0
                           245.0    276.0
America/New_York           339.0    912.0

In [49]:
agg_counts.sum(1).nlargest(10)

tz
America/New_York       1251.0
                        521.0
America/Chicago         400.0
America/Los_Angeles     382.0
America/Denver          191.0
Europe/London            74.0
Asia/Tokyo               37.0
Pacific/Honolulu         36.0
Europe/Madrid            35.0
America/Sao_Paulo        33.0
dtype: float64

In [50]:
subset = count_subset.stack()

In [51]:
subset

tz                   os         
America/Sao_Paulo    Not Windows     13.0
                     Windows         20.0
Europe/Madrid        Not Windows     16.0
                     Windows         19.0
Pacific/Honolulu     Not Windows      0.0
                     Windows         36.0
Asia/Tokyo           Not Windows      2.0
                     Windows         35.0
Europe/London        Not Windows     43.0
                     Windows         31.0
America/Denver       Not Windows    132.0
                     Windows         59.0
America/Los_Angeles  Not Windows    130.0
                     Windows        252.0
America/Chicago      Not Windows    115.0
                     Windows        285.0
                     Not Windows    245.0
                     Windows        276.0
America/New_York     Not Windows    339.0
                     Windows        912.0
dtype: float64

In [52]:
 count_subset

os                   Not Windows  Windows
tz                                       
America/Sao_Paulo           13.0     20.0
Europe/Madrid               16.0     19.0
Pacific/Honolulu             0.0     36.0
Asia/Tokyo                   2.0     35.0
Europe/London               43.0     31.0
America/Denver             132.0     59.0
America/Los_Angeles        130.0    252.0
America/Chicago            115.0    285.0
                           245.0    276.0
America/New_York           339.0    912.0